export const GET_HOTELS_REQUESTED = 'GET_HOTELS_REQUESTED';
export const GET_HOTELS_SUCCESS = 'GET_HOTELS_SUCCESS';
export const GET_HOTELS_ERROR = 'GET_HOTELS_ERROR';

export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
